# syntax=docker/dockerfile:1
FROM golang:1.22.1 AS builder
WORKDIR /src
COPY ./client .
RUN go mod tidy && CGO_ENABLED=0 go build -o /bin/example ./tcp_client.go

FROM scratch
COPY --from=builder /bin/example /bin/tcp_client
CMD ["/bin/tcp_client"]
