# syntax=docker/dockerfile:1
FROM golang:1.22.1 AS builder
WORKDIR /src
COPY ./tcp_server .
RUN go mod tidy && CGO_ENABLED=0 go build -o /bin/example ./tcp_server.go

FROM scratch
COPY --from=builder /bin/example /bin/tcp_server
CMD ["/bin/tcp_server"]
